[package]
name = "sl-oblivious"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.3" }
thiserror = "1"
sl-mpc-mate = {path ="../sl-mpc-mate" }
blake3 = { version = "1.4", features = ["pure"] }
merlin = "3.0.0"
elliptic-curve = { version ="0.13" }
k256 = {version = "0.13", features = [ "ecdsa" ]}
rand = "0.8"
sha3 = "0.10.8"
# rayon = "1"
