[package]
name = "sl-oblivious"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
sl-mpc-mate = {path ="../sl-mpc-mate", features =["nacl"]}
blake3 = { version = "1.4", features = ["pure"] }
serde = {version = "1", features = ["derive"]}
merlin = "3.0.0"
elliptic-curve = {version ="0.13", features=["serde"]}
k256 = {version = "0.13", features = ["serde", "ecdsa"]}
# rayon = "1"
rand = "0.8"
sha3 = "0.10.8"
serde_arrays = "0.1.0"
colored = "2.0.0"
hex = "0.4.3"
serde_json = "1.0.97"

[dev-dependencies]
