[package]
name = "sl-oblivious"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thiserror = "1"
sl-mpc-mate = {path ="../sl-mpc-mate" }
merlin = "3.0.0"
elliptic-curve = { version ="0.13" }
k256 = { version = "0.13", default-features = false, features = [ "arithmetic" ]}
rand = "0.8"
rayon = "1"
x25519-dalek = { version = "2.0.0", features = [ "reusable_secrets", "zeroize" ] }
zeroize = "1.6.1"
bytemuck = { version = "1.14.1", features = [ "derive", "min_const_generics", "extern_crate_alloc" ] }
