[package]
name = "sl-mpc-mate"
version = "0.1.0"
edition = "2021"
description = "Utilities for secure multi-party computation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version ="1", features = ["derive"]}
bincode = "1"
rand_core = "0.6"
elliptic-curve = {version ="0.13", features=["serde"]}
dryoc = {version = "0.5.0", features=["serde"], optional = true}
rayon = '1'


[dev-dependencies]
k256 = {version = "0.13", features = ["serde", "ecdsa"]}


[features]
nacl = ["dryoc"]
