[package]
name = "sl-mpc-mate"
version = "0.1.0"
edition = "2021"
description = "Utilities for secure multi-party computation"

[dependencies]
# arrayref = "0.3"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
generic-array = { version = "0.14.7" }
# futures-util = { version = "0.3.28" }
tokio = { version = "1", features = ["rt", "sync", "time"] }
aead = { version = "0.5.2" }
chacha20 = { version = "0.9" }
chacha20poly1305 = { version = "0.10.1" }
x25519-dalek = { version = "2.0.0", features = [ "reusable_secrets" ] }
ed25519-dalek = { version = "2.0.0" }
sha2 = { version = "0.10" }
digest = { version = "0.10" }
rand = "0.8.5"
serde = {version ="1", features = ["derive"]}
rand_core = "0.6"
elliptic-curve = {version ="0.13", features=["serde"]}
subtle = { version = "2.5", default-features = false, features = ["const-generics"] }
dryoc = {version = "0.5.0", features=["serde"], optional = true}
# rayon = '1'

[dev-dependencies]
tokio = { version = "1", features = ["rt", "sync", "macros" ] }
k256 = {version = "0.13", features = ["serde", "ecdsa"]}


[features]
nacl = ["dryoc"]
